import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";
import { SiteHeader } from "@/components/site-header";
import Provider from "@/app/context/client-provider";
import { getServerSession } from "next-auth/next";
import { options } from "./api/auth/[...nextauth]/options";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SiteHeader />
            <main className="container mx-auto min-h-[calc(100vh-122px)] p-5">
              {children}
            </main>
            <Toaster position="bottom-left" />
            <Footer />
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
